### ISSUE TITLE
Questions about dimensionality

### ISSUE THREAD

**Issue by eventhorizon7** [juyongjiang/DAAGCN#1]
https://github.com/juyongjiang/DAAGCN/blob/ddc775a5fc6ee3cc1cb81c878c74f463be0b4b5b/dataloader.py#L58

Hello!
Thank you very much for your open source, I am very interested in your work
I was looking at the code and noticed that a dimension was added here, but didn't understand it, I hope you can tell me what it does

**Comment by juyongjiang** [comment]
> https://github.com/juyongjiang/DAAGCN/blob/ddc775a5fc6ee3cc1cb81c878c74f463be0b4b5b/dataloader.py#L58
> 
> Hello! Thank you very much for your open source, I am very interested in your work I was looking at the code and noticed that a dimension was added here, but didn't understand it, I hope you can tell me what it does

Hi~ thanks for your great interest and questions! 
Here, we only use one traffic data feature, i.e., traffic flow, so the shape of data will be [:, :, 0]->[B, N]. However, to maintain the requirement of dimension in GCN operation, we need to expand the last dimension as [B, N, 1], which means that the last dimension is the feature dimension. This processing is a very common operation. Hope it can help you solve your question. : ) 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/50765248/184308399-eb4771a5-5651-4dee-972a-b4a2b1045e4d.png">

**Comment by Dong-sa** [comment]
Hello!
Thank you very much for your open source, I am very interested in your work
May I ask how to set up a DAAGCN model that only uses Dynamic adaptive graph instead of static graph?

**Comment by juyongjiang** [comment]
> Hello! Thank you very much for your open source, I am very interested in your work May I ask how to set up a DAAGCN model that only uses Dynamic adaptive graph instead of static graph?

@Dong-sa Thanks for your
