### ISSUE TITLE
About the implementation of 'Time Series Correlation' in figure 3.

### ISSUE THREAD

**Issue by 1ofsomepeople** [juyongjiang/DAAGCN#2]
Hi, juyong!
Thanks for the open source code! I've read your paper and I notice that the 'Graph Level' Discriminator implemented in this repo seems doesn't use 'Time Series Correlation' which appears in figure 3 of the paper. Did I miss something?

**Comment by juyongjiang** [comment]
> Hi, juyong! Thanks for the open source code! I've read your paper and I notice that the 'Graph Level' Discriminator implemented in this repo seems doesn't use 'Time Series Correlation' which appears in figure 3 of the paper. Did I miss something?

Hi, thanks for your interest! In here, the time series correlation is constructed as a graph with softmax normalization. Then, a discriminator distinguishes whether predicted traffic series have the same time series correlation as ground truth, this discriminator can be viewed as 'Graph Level' discriminator. Hope it is more clear. : )
<img width="965" alt="image" src="https://user-images.githubusercontent.com/50765248/186739366-764629c7-ae0b-4828-bea7-d10a803dc5bf.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/50765248/186739557-208fe47a-d6ed-4f79-8146-10405fc74916.png">

**Comment by 1ofsomepeople** [comment]
Thanks reply! You have solved my problem!
